### ISSUE TITLE
'transition' mixin not included in SASS files

### ISSUE THREAD

**Issue by bbisinger** [djett41/ionic-filter-bar#11]
Compiling ionic.filter.bar.scss throws an error on line 31
"@include transition(opacity 150ms ease-in-out);"

**Comment by djett41** [comment]
@captainjim1 make sure you're also including the ionic sass import since the ionic-filter-bar depends on ionic.  look at the demo/styles/main.scss file for an exmaple.. there you will see the ionic sass is imported before the filter bar sass.  This way we have access to al of the ionic mixins and nav bar variables so we dont have duplicated code.

**Comment by bbisinger** [comment]
Hmm.. I guess I have a different issue then. I'm using gulp-sass with watchify to recompile everything whenever a change occurs. Ionic compiles just fine, but when I add your sass as an entry point it obviously doesn't know about the ionic sass.. I'll look into my options...

**Comment by djett41** [comment]
got ya.  im not too familiar with watchify but if your watch task watches individual files and then compiles the main file (which includes ionic, filter-bar, and any other custom scss) then it should be fine.  If your watcher is trying to compile individual files rather than the main file which includes imports then I could see that potentially being an issue.

Let me know what you find out.

**Comment by djett41** [comment]
I'm just using gulp.watch which will then run the styles task when a change is detected.  This recompiles the main file with no errors.

```
gulp.watch('app/styles/**/*.scss', ['styles']);
```

perhaps you could still use gulp.watch for your scss files while using watchify for your other watches as shown here https://truongtx.me/2014/08/06/using-watchify-with-gulp-for-fast-browserify-build/

**Comment by bbisinger** [comment]
Adding a main sass file that imports everything else fixed my problem .. not sure how I failed to that in the first place.

**Comment by djett41** [comment]
nice! Just make sure that main file that gets compiled is the only css imported in your index, rather than importing ionic css AND your main compiled css that also includes the ionic css.

**Comment by bbisinger** [comment]
Yep -- all of my different sass roots are in imported in one file... just one css file is created and that one css file is all that's loaded by my site. Thanks again!

**Comment by djett41** [comment]
Great.  No prob!  I;m going to close this issue
