### ISSUE TITLE
How to use it with promise?

### ISSUE THREAD

**Issue by arbh89** [djett41/ionic-filter-bar#18]
How can i use this awesome filter bar from a promise?

**Comment by djett41** [comment]
Thanks @arbh89 .  Since I'm returning a function that you can use to manually cancel, the filter bar does not return a promise.  However you can pass in callbacks when the filterBar is finished showing, or removed.

See the docs for more info but assigning a function to the "done" property will run your odne function when the filterBar is shown, adding to "cancel" will be called when the filterbar is removed.

If your function that uses ionicFilterBar uses promises, you can resolve your promise within the cancel or done callbacks

**Comment by arbh89** [comment]
Thanks @djett41, this is my scenario, i want to populate a list from a promise using the filter bar, this means that i don't have initial items to filter, how can i achieve this? if you have an example would be better.

**Comment by djett41** [comment]
Its hard to understand what exactly you want to accomplish without seeing your controller code, but you could 

A) get all of your list data when your view initializes in your controller so when you click the search button you will already have the items to filter on
B) If you HAVE to get data async on click, then just wait until you resolve your data to show the filter bar, but this probably wouldnt be the best use experience.  You need to already have your data resolved and on your scope before showing the filter bar.  See demo for an exampe
