### ISSUE TITLE
filterProperties example

### ISSUE THREAD

**Issue by EricDosReis** [djett41/ionic-filter-bar#23]
I'm trying to set filtering properties of my object, but it's not working. This is my code:
- Array of objects

``` javascript
[{
    ID: "11944", 
    NAME: "ANNA PATRICIA", 
    RAZAO_SOCIAL: "ANNA PATRICIA", 
    CNPJ: "27442367000111"
}, {
    ID: "11943", 
    NAME: "BEBIDAS IPIRANGA", 
    RAZAO_SOCIAL: "BEBIDAS IPIRANGA", 
    CNPJ: "16227158000139"
}]
```
- Filter bar function

``` javascript
$scope.showFilterBar = function() {
    $ionicFilterBar.show({
        items: $scope.clientes,
        filterProperties: ['ID', 'NAME', 'CNPJ'],
        cancelText: 'Cancelar',
        update: function(filteredItems) {
            $scope.clientes = filteredItems;
        }
    });
}
```

What are I doing wrong?
Can you give me an example?

**Comment by EricDosReis** [comment]
I was reading some closed issues and I find my answer on a comment you made.

Link: https://github.com/djett41/ionic-filter-bar/issues/12

"if you were to supply filterProperties: ['name', 'text'] and your search input was 'rebel', you would get no results. This is because the angular filter would check for the text on ALL properties."

Filter all properties is so good, because I provide to the user all the options to find the data.

Thanks so much and I'm sorry for my lack of attention.

**Comment by djett41** [comment]
no prob @EricDosReis .  There have been quite a few questions relating to this topic, which is an indicator that my documentation is not good enough.  I just re-read it and I'll admit it's kind of confusing haha.

I'll update the DOCS, but the filter properties basically creates a filter expression object with each item in the array and has default angular filter functionality...

But since it seems alot of people are looking for OR functionality with filterProperties, I may change this or at least add like a filterExpressionType (OR or AND) or something like that.. I myself use an OR style filter, and pass in a custom filter, but it would be nice to just ad this functionality to the product.

Thanks!
