### ISSUE TITLE
Access to filter string

### ISSUE THREAD

**Issue by ingopansa** [djett41/ionic-filter-bar#24]
Hi,

I'm wondering if/how it is possible to access the filter string. Maybe I missed something, but I did not find an option to operate on the filter string. 

In particular, I want to switch views, depending on the size of the filter string. For instance, if the length of the filter string is zero, I need to display a trending searches view.

Ingo

**Comment by djett41** [comment]
You didn't miss anything @ingopansa.  Where would you need it?  The only place I could pass it that would make sense is in the update callback..

so `update` could have two arguments pssed both the filtered items, and the filterText.

Would that give you what you need? I don't see anywhere else where it would make sense passing it to, and since ionicFilterBar has an isolate scope, you wouldnt be able to access it from your controller.

**Comment by ingopansa** [comment]
Putting it in the update call would definitely make sense, as this function gets called when the search results are being updated. Separating it from the update callback and having a separate option for it would make sense for the use cases where you need to know the search string independently from updating the search results. 

So, I would say: It depends on where you want to have it :)

For me, the update-callback solution would perfectly work.

**Comment by djett41** [comment]
Yeah I think update is where I am going to pass it back to

**Comment by djett41** [comment]
This has been added!  Thanks agin!

**Comment by ingopansa** [comment]
thanks - will test it out the next days and provide feedback.

ip
