### ISSUE TITLE
Support for custom filter function

### ISSUE THREAD

**Issue by jayagl** [djett41/ionic-filter-bar#25]
Hi. Thanks for your work. It has been very useful. This is not really an issue but I think there should be a way to supply a custom filter function, which gets called with the arguments `filterText, item, index, array` and returns true if item passes.
It would be easy to do. If `filterProperties` is a function then bind `filterText` as an argument and pass it to angular filter. Something like this maybe:

``` javascript
          scope.filterItems = function(filterText) {
            var filterExp, filteredItems;

            // pass back original list if filterText is empty.  Otherwise filter by supplied properties, or filterText
            if (!filterText.length) {
              filteredItems = scope.items;
            } else {
              if (angular.isFunction(scope.filterProperties)) {  
                filterExp = angular.bind(this, scope.filterProperties, filterText);  
              } else if (angular.isArray(scope.filterProperties)) {
                filterExp = {};
                angular.forEach(scope.filterProperties, function (property) {
                  filterExp[property] = filterText;
                });
              } else if (scope.filterProperties) {
                filterExp = {};
                filterExp[scope.filterProperties] = filterText;
              } else {
                filterExp = filterText;
              }

              filteredItems = scope.filter(scope.items, filterExp);
            }

            $timeout(function() {
              scope.update(filteredItems);
              scope.scrollItemsTop();
            });
          };

```

**Comment by djett41** [comment]
thanks @jayagl .  I have been giving this some thought over the last few days and I am thinking that instead of having a filterProperties option, which dynamically creates the filterExpression but is kind of limited, I may just add filterExpression, and comparator as options, and in the scope.filterItems function always call scope.filter(scope.items, scope.filterExpression, scope.comparator); or something similar.

This way we can mimic the same behavior that angular gives you out of the box, rather than trying to reinvent the wheel or dynamically create a filterExpresion which is limited (which is how it is now).

Seems like this would give the most flexibility!  Your thoughts?

**Comment by jayagl** [comment]
Not sure I understand. If you directly pass the comparator and filterExpression then how does one reference the filterText? Are you going to parametrize it? In which case you would be kind of doing what you are doing now.

**Comment by djett41** [comment]
You're right @jayagl that doesnt make sense now that I think about it.  Let me give it some thought and try to come up with a solution that might suit everyones needs including the solution you have suggested supporting function expressions

**Comment by jayagl** [comment]
Cool, no worries. I think you can achieve full flexibility as far as the angular filter function goes by using the above approach for function expressions and then allowing a comparator function to be specified as an option and passing that on to filter().

**Comment by djett41** [comment]
I think you're right @jayagl . That should be sufficient, I would like to also add an OR search functionality using the filterProperties
